### ISSUE TITLE
url_for generates links differently when using "yard server" and "yardoc"

### ISSUE THREAD

**Issue by nitinmohan87** [lsegal/yard#663] opened 2013-04-03 20:34 UTC
I have an object which is of type CookbookObject (inherited from ChefObject). This object is under the namespace "ChefObject" (inherited from ClassObject). I am trying to create a link using "url_for" method as follows

```ruby
class ChefObject < YARD::CodeObjects::ClassObject; end
class CookbookObject < ChefObject; end

chef = ChefObject.new(:root, 'Chef')
cookbook = CookbookObject.new(chef, 'app')

url_for(cookbook, "anchor")  #  returns "Chef/app.html#anchor" 
# when generated via yard server. NOTE: This is the expected output.
url_for(cookbook, "anchor")  #  returns "app.html#anchor" when using yardoc
```

Why is this difference when using "yardoc" and "yard server"? Or am I doing something wrong here?

**Comment by lsegal** [comment] 2016-07-07 23:40
I'm marking this as closed since this is extremely old. Feel free to re-open if you are still having this issue, but please try to provide a minimal case that reproduces the problem. Right now there are too many missing details to determine if the root cause is YARD or some plugin code you may have been working on. Running a little test of my own seems to generate correct HTML links for app.html in the class list, which makes me thing `url_for` is working fine:

```ruby
require 'yard'

class ChefObject < YARD::CodeObjects::ClassObject; end
class CookbookObject < ChefObject; end

YARD::Registry.delete_from_disk
chef = ChefObject.new(:root, 'Chef')
cookbook = CookbookObject.new(chef, 'app')
YARD::Registry.save(true)
YARD::CLI::Yardoc.run('-c', '--debug')
```

It's possible you may be doing something with urls, or changing the `object` in your template. It's also possible you're using url_for in a context where `object` is set but the page you are generating is not inside of the `object`'s HTML file-- in the latter convoluted case, YARD will generate a relative link to `app.html` (since it thinks you are in `Chef/`) but this link might be used elsewhere.

**Closed by lsegal** 2016-07-07 23:40 UTC
Labels: Bug
