### ISSUE TITLE
Ruby Core Math class parsing issue

### ISSUE THREAD

**Issue by MSP-Greg** [lsegal/yard#992] opened 2016-07-21 02:30 UTC
I will (next day or two) look thru my code to see how I got the c parser to correctly parse the Math class.

See:

https://msp-greg.github.io/Ruby-2.3/Core/Math.html

vs

http://www.rubydoc.info/stdlib/core/Math

**Comment by lsegal** [comment] 2016-07-21 06:30
`math.h` seems to parse fine in YARD 0.9.3. rubydoc.info hasn't updated the yard db for stdlib in a while.

**Comment by lsegal** [comment] 2016-07-21 19:25
Marking this as working as intended. The docs on rubydoc.info needed updating (they were only at 2.2.2). This is now resolved.

**Closed by lsegal** 2016-07-21 19:25 UTC
