### ISSUE TITLE
Server hangs with Ruby 2.4

### ISSUE THREAD

**Issue by MaxPleaner** [lsegal/yard#951] opened 2016-03-18 19:02 UTC
Not sure if this is really an issue you're concerned about, as Ruby 2.4 is still in development.

But the `yard server` command hangs with this version.

The command line shows the server starting up OK but connecting to `localhost:8808` never renders a HTML page. 

This issue is resolved by using ruby 2.2 instead.

Feel free to close this issue if you'd rather test against stable rubies only.

**Comment by lsegal** [comment] 2016-03-19 18:57
Closing this dupe of #950

**Closed by lsegal** 2016-03-19 18:57 UTC
