### ISSUE TITLE
On extra files problems

### ISSUE THREAD

**Issue by zverok** [lsegal/yard#1026] opened 2016-10-06 11:03 UTC
A question (and possible topic for PR?), not a bug again.

YARD has an ability to add extra files to docs.
But it seems there are not enough features for our usage.

Situation is: we have a large and detailed README.md, which besides text has also:
* schemas (from PNG) files;
* links to other .md files in `docs/` subfolder;
* links to sections of itself.

All of those are working OK in GitHub UI, but not really well with YARD:
* `schema.png`, being added to list of files, is treated by YARD as text file and rendered into something inappropriate;
* Links like `[installation](docs/install.md)` are left intact, despite the fact that "docs/install.md" is added to extra files list (I expect URL to be rewritten to `file.install.html` or something);
* It looks like you can't add `docs/**/*.md` to extra files list, just list them all one by one;
* YARD renders different section ids in large Markdown file, than GitHub ("Routes Overview" => "#routes-overview" in GitHub but "#Routes_Overview" in YARD), so there is no way to make links to sections working on both;
* If we have several files with the same names (`./README.md` vs `app/controllers/README.md`), they all rendered to `file.README.html` path; OK, approach of having several READMEs in deep folders is questionable, yet widely used.

Would you accept a PRs, fixing some or all of those problems? (The last two may be controversial: changing link anchors could break older links, but we can do an option, maybe? And handling directory structure for extra files also looks like something that can introduce breaking changes.)

**Comment by lsegal** [comment] 2016-10-06 18:25
Hey,

I'll answer this point by point, but tl;dr most of these are expected behaviors:

> schema.png, being added to list of files, is treated by YARD as text file and rendered into something inappropriate;

Binary files should not be added to your extra files list. Use `--asset` to hook up assets. It's more complicated than just listing a file because the output location is not guaranteed to be the same across rendering environments (local filesystem vs. yard server).

> Links like `[installation](docs/install.md)` are left intact, despite the fact that "docs/install.md" is added to extra files list (I expect URL to be rewritten to file.install.html or something);

YARD does *not* touch your markup. It only touches its own markup syntax to link files ([use `{file:path/to/file}`](http://www.rubydoc.info/gems/yard/file/docs/GettingStarted.md#Linking_Files__file_____)). You should not rely on markdown links. Just as above, the locations of your files may change depending on the rendering context used (yard server does not have a .html extension, for example).

If you have a requirement where you must use markdown links, you can write a YARD extension to linkify these special URLs yourself (convert any `<a>` link pointing to doc/, for example). I recall someone writing this just recently but I forget where it was brought up (might have been IRC).

YARD *could* do post-processing on `<a>` links to rewrite any `src`es that exactly match a relative link to an extra file path. A PR for this would be acceptable.

> It looks like you can't add docs/**/*.md to extra files list, just list them all one by one;

This isn't accurate. YARD [supports globbing on extra files](https://github.com/lsegal/yard/blob/master/lib/yard/cli/yardoc.rb#L404). The issue is that you typically *don't want* arbitrary file listing order in your extra file listing, since you want control of the order in which users see these documents. A "Getting Started" document would be near the top, for example. That's why YARD lists its own files explicitly. In addition, YARD's `guide` template explicitly relies on ordering for its section mapping. 

So globbing is supported but you shouldn't be relying on it. It's fine for testing, but you should lock down the file order before publishing documentation.

> YARD renders different section ids in large Markdown file, than GitHub

As you noted, this would be a breaking change and not going to be considered. It's also arbitrary, since this would fix things for GitHub users but not for Bitbucket users, or any other markdown hosting site. This, again, is a great scenario for writing a specialized plugin for your problem. A `yard-github` plugin, for instance, could deal with these issues in a generalized fashion.

You could also write a non-YARD tool to post process the HTML files, of course.

> If we have several files with the same names (./README.md vs app/controllers/README.md), they all rendered to file.README.html path;

This is a known issue but also a breaking change and can't be modified. There are a number of workarounds for this case, but there are no plans to address this directly in YARD.

**Comment by zverok** [comment] 2016-10-07 12:13
OK, thanks for clarifications.

**Comment by lsegal** [comment] 2016-10-21 19:42
I'm going to close this issue since it's a question and has been answered. That said, a feature to detect relative `<a>` links in markup processing would be acceptable as a PR if someone was interested.

**Closed by lsegal** 2016-10-21 19:42 UTC
