### ISSUE TITLE
What does YARD blow-up on this #extend call?

### ISSUE THREAD

**Issue by trans** [lsegal/yard#475] opened 2012-01-27 22:54 UTC
Here's the issue I made about it (to the wrong project though): https://github.com/blackwinter/brice/issues/5

Here's the file: https://github.com/blackwinter/ruby-nuggets/blob/master/lib/nuggets/env/set.rb

**Comment by lsegal** [comment] 2016-07-08 23:55
I'm closing this since Nuggets doesn't seem to have parsing problems anymore. I'm not inclined to change anything here because at best we can just turn the error into a warning, which does nothing to actually resolve the root cause, and realistically that kind of error would crop up in many other places, so the fix wouldn't be 100% reliable anyway. I think the workaround here is to simply notify authors of these doc issues, because they are fairly easy to workaround in code (defining a module first) or via `.yardopts` (setting explicit parse order). PRs can even be submitted to these projects.

**Closed by lsegal** 2016-07-08 23:55 UTC
Labels: Bug
