### ISSUE TITLE
@param and @return descriptions not visible on rubydoc.info

### ISSUE THREAD

**Issue by tf** [lsegal/yard#1293] opened 2019-12-07 09:04 UTC
For example, [`Yard::Config#load_plugin`](https://github.com/lsegal/yard/blob/ebd6269df6d9d12d4dce0fae53fbf80dfe7d5c4f/lib/yard/config.rb#L157) has a `@param` tag that describes the `name` param and a `@return` tag which describes the returned boolean. 

Neither are visible in the [generated docs](https://www.rubydoc.info/gems/yard/YARD%2FConfig.load_plugin) on rubydoc.info. I was not able to find a gem were params are still included. I believe this is not the intended behavior, right?

**Comment by lsegal** [comment] 2020-01-02 19:47
This seems to be working correctly on rubydoc.info now. It's possible this issue was fixed in the latest release, so I will mark this as closed.

If you see this behavior elsewhere in 0.9.22+, feel free to reopen this issue or file a new one with a reproduction case.

**Closed by lsegal** 2020-01-02 19:47 UTC
