### ISSUE TITLE
An error raised under Ruby 2.2.0

### ISSUE THREAD

**Issue by nepalez** [lsegal/yard#834] opened 2015-02-03 08:50 UTC
Yard raises an error under Ruby 2.2.0

    yard
    [warn]: @param tag has unknown parameter name: source 
        in file `lib/hexx/validators/parsers/validator.rb' near line 14
    /.rvm/gems/ruby-2.2.0/gems/yard-0.8.7.6/lib/yard/parser/ruby/ruby_parser.rb:460:in `block (2 levels) in on_params': undefined method `type' for 6264:Fixnum (NoMethodError)
    from /.rvm/gems/ruby-2.2.0/gems/yard-0.8.7.6/lib/yard/parser/ruby/ruby_parser.rb:458:in `map!'
    from /.rvm/gems/ruby-2.2.0/gems/yard-0.8.7.6/lib/yard/parser/ruby/ruby_parser.rb:458:in `block in on_params'
    from /.rvm/gems/ruby-2.2.0/gems/yard-0.8.7.6/lib/yard/parser/ruby/ruby_parser.rb:454:in `map!'
    from /.rvm/gems/ruby-2.2.0/gems/yard-0.8.7.6/lib/yard/parser/ruby/ruby_parser.rb:454:in `on_params'
    from /.rvm/gems/ruby-2.2.0/gems/yard-0.8.7.6/lib/yard/parser/ruby/ruby_parser.rb:50:in `parse'
    from /.rvm/gems/ruby-2.2.0/gems/yard-0.8.7.6/lib/yard/parser/ruby/ruby_parser.rb:50:in `parse'
    from /.rvm/gems/ruby-2.2.0/gems/yard-0.8.7.6/lib/yard/parser/ruby/ruby_parser.rb:15:in `parse'
    from /.rvm/gems/ruby-2.2.0/gems/yard-0.8.7.6/lib/yard/parser/source_parser.rb:439:in `parse'
    from /.rvm/gems/ruby-2.2.0/gems/yard-0.8.7.6/lib/yard/parser/source_parser.rb:44:in `block in parse'
    from /.rvm/gems/ruby-2.2.0/gems/yard-0.8.7.6/lib/yard/logging.rb:70:in `capture'
    from /.rvm/gems/ruby-2.2.0/gems/yard-0.8.7.6/lib/yard/parser/source_parser.rb:43:in `parse'
    from /.rvm/gems/ruby-2.2.0/gems/yard-0.8.7.6/lib/yard/parser/source_parser.rb:368:in `parse_in_order'
    from /.rvm/gems/ruby-2.2.0/gems/yard-0.8.7.6/lib/yard/parser/source_parser.rb:107:in `block in parse'
    from /.rvm/gems/ruby-2.2.0/gems/yard-0.8.7.6/lib/yard/logging.rb:166:in `enter_level'
    from /.rvm/gems/ruby-2.2.0/gems/yard-0.8.7.6/lib/yard/parser/source_parser.rb:106:in `parse'
    from /.rvm/gems/ruby-2.2.0/gems/yard-0.8.7.6/lib/yard.rb:18:in `parse'
    from /.rvm/gems/ruby-2.2.0/gems/yard-0.8.7.6/lib/yard/cli/yardoc.rb:249:in `run'
    from /.rvm/gems/ruby-2.2.0/gems/yard-0.8.7.6/lib/yard/cli/command.rb:13:in `run'
    from /.rvm/gems/ruby-2.2.0/gems/yard-0.8.7.6/lib/yard/cli/command_parser.rb:71:in `run'
    from /.rvm/gems/ruby-2.2.0/gems/yard-0.8.7.6/lib/yard/cli/command_parser.rb:53:in `run'
    from /.rvm/gems/ruby-2.2.0/gems/yard-0.8.7.6/bin/yard:12:in `<top (required)>'
    from /.rvm/gems/ruby-2.2.0/bin/yard:23:in `load'
    from /.rvm/gems/ruby-2.2.0/bin/yard:23:in `<main>'
    from /.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `eval'
    from /.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `<main>'

The code that causes an error:

    # lib/hexx/validators/parsers/validator.rb
    ...
    10  # @api hide
    11  # Initializes the parser object.
    12  # @param  [String] source The validator name to parse.
    13  # @return [Hexx::Validators::Parsers::Validator]
    14  def initialize(validator)
    15    @validator = validator.to_s
    16  end

The exception is raised under Ruby 2.2.0 (here and there, the code above is just an example) and is absent in Ruby 2.1.2.

**Comment by lsegal** [comment] 2015-02-03 09:01
Dupe of #825. 2.2.0p0 has a bug that breaks YARD. :(

**Closed by lsegal** 2015-02-03 09:01 UTC
