### ISSUE TITLE
yard aborts with undefined method `length' for nil:NilClass, at ruby_parser.rb

### ISSUE THREAD

**Issue by sriv** [lsegal/yard#835] opened 2015-02-09 13:51 UTC
While using ruby-2.2.0, and yard-0.8.7.6 on a project for the first time, I encountered this:

```
steam$ rake yard
rake aborted!
NoMethodError: undefined method `length' for nil:NilClass
/Users/steam/.rvm/gems/ruby-2.2.0/gems/yard-0.8.7.6/lib/yard/parser/ruby/ruby_parser.rb:210:in `on_ignored_nl'
/Users/steam/.rvm/gems/ruby-2.2.0/gems/yard-0.8.7.6/lib/yard/parser/ruby/ruby_parser.rb:50:in `parse'
/Users/steam/.rvm/gems/ruby-2.2.0/gems/yard-0.8.7.6/lib/yard/parser/ruby/ruby_parser.rb:50:in `parse'
/Users/steam/.rvm/gems/ruby-2.2.0/gems/yard-0.8.7.6/lib/yard/parser/ruby/ruby_parser.rb:15:in `parse'
/Users/steam/.rvm/gems/ruby-2.2.0/gems/yard-0.8.7.6/lib/yard/parser/source_parser.rb:439:in `parse'
/Users/steam/.rvm/gems/ruby-2.2.0/gems/yard-0.8.7.6/lib/yard/parser/source_parser.rb:44:in `block in parse'
/Users/steam/.rvm/gems/ruby-2.2.0/gems/yard-0.8.7.6/lib/yard/logging.rb:70:in `capture'
/Users/steam/.rvm/gems/ruby-2.2.0/gems/yard-0.8.7.6/lib/yard/parser/source_parser.rb:43:in `parse'
/Users/steam/.rvm/gems/ruby-2.2.0/gems/yard-0.8.7.6/lib/yard/parser/source_parser.rb:368:in `parse_in_order'
/Users/steam/.rvm/gems/ruby-2.2.0/gems/yard-0.8.7.6/lib/yard/parser/source_parser.rb:107:in `block in parse'
/Users/steam/.rvm/gems/ruby-2.2.0/gems/yard-0.8.7.6/lib/yard/logging.rb:166:in `enter_level'
/Users/steam/.rvm/gems/ruby-2.2.0/gems/yard-0.8.7.6/lib/yard/parser/source_parser.rb:106:in `parse'
/Users/steam/.rvm/gems/ruby-2.2.0/gems/yard-0.8.7.6/lib/yard.rb:18:in `parse'
/Users/steam/.rvm/gems/ruby-2.2.0/gems/yard-0.8.7.6/lib/yard/cli/yardoc.rb:249:in `run'
/Users/steam/.rvm/gems/ruby-2.2.0/gems/yard-0.8.7.6/lib/yard/rake/yardoc_task.rb:74:in `block in define'
Tasks: TOP => yard
(See full trace by running task with --trace)
```

Any tips?

**Comment by sriv** [comment] 2015-02-10 07:21
`yard --debug` helped me track this down.

I figured that this was caused when you have a multi-line code, and documentation inserted in between.

In my case I had the below line, which yard didn't like:

```
rewriter.replace(ast.children[1].location.expression, new_params_string) #insert new arguments
  .process
```

**Comment by lsegal** [comment] 2015-02-10 07:31
Reopening. This is a legitimate bug.

**Comment by nobuf** [comment] 2015-04-30 02:13
I've faced the same error. As @sriv mentioned, I have the same `code... # comment` in a file.
```
$ ruby -v
ruby 2.2.1p85 (2015-02-26 revision 49769) [x86_64-darwin14]
$ yardoc --version
yard 0.8.7.6
```
```
/Users/nobu/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/yard-0.8.7.6/lib/yard/parser/ruby/ruby_parser.rb:210:in `on_ignored_nl': undefined method `length' for nil:NilClass (NoMethodError)
        from /Users/nobu/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/yard-0.8.7.6/lib/yard/parser/ruby/ruby_parser.rb:50:in `parse'
```

**Comment by tjchambers** [comment] 2015-05-15 16:09
I too have faced the same error. As @sriv mentioned, I have the same code... # comment in a file. I have adjusted the commenting

**Comment by lsegal** [comment] 2015-05-15 16:33
This is actually a bug in Ruby and duplicate of #825

**Closed by lsegal** 2015-05-15 16:33 UTC

**Comment by nobuf** [comment] 2015-05-16 05:02
I still get the below error with `2.2.1p85` and `2.2.2p95` (and it's a different error from #825):
```
$ ruby -v
ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-darwin14]
$ cat a.rb
puts [1, 1]
  .uniq #
  .size
$ ruby a.rb
1
$ yardoc --debug a.rb
[debug]: Parsing ["a.rb"] with `ruby` parser
[debug]: Parsing a.rb
/Users/nobu/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/yard-0.8.7.6/lib/yard/parser/ruby/ruby_parser.rb:210:in `on_ignored_nl': undefined method `length' for nil:NilClass (NoMethodError)
        from /Users/nobu/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/yard-0.8.7.6/lib/yard/parser/ruby/ruby_parser.rb:50:in `parse'
$ cat b.rb
puts [1, 1]
  .uniq
  .size
$ yardoc --debug b.rb
...skip
 100.00% documented
```

I noticed that without the third line (`.size`) it parsed with no error too.
Am I missing something?

**Comment by aquach** [comment] 2015-12-08 03:59
I'm seeing this in Ruby 2.2.2 and Yard 0.8.7.6. I think that's this bug?

```
/home/alex/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/yard-0.8.7.6/lib/yard/parser/ruby/ruby_parser.rb:210:in `on_ignored_nl': undefined method `length' for nil:NilClass (NoMethodError)
	from /home/alex/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/yard-0.8.7.6/lib/yard/parser/ruby/ruby_parser.rb:50:in `parse'
	from /home/alex/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/yard-0.8.7.6/lib/yard/parser/ruby/ruby_parser.rb:50:in `parse'
	from /home/alex/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/yard-0.8.7.6/lib/yard/parser/ruby/ruby_parser.rb:15:in `parse'
	from /home/alex/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/yard-0.8.7.6/lib/yard/parser/source_parser.rb:439:in `parse'
	from /home/alex/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/yard-0.8.7.6/lib/yard/parser/source_parser.rb:44:in `block in parse'
	from /home/alex/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/yard-0.8.7.6/lib/yard/logging.rb:70:in `capture'
	from /home/alex/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/yard-0.8.7.6/lib/yard/parser/source_parser.rb:43:in `parse'
	from /home/alex/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/yard-0.8.7.6/lib/yard/parser/source_parser.rb:368:in `parse_in_order'
	from /home/alex/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/yard-0.8.7.6/lib/yard/parser/source_parser.rb:107:in `block in parse'
	from /home/alex/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/yard-0.8.7.6/lib/yard/logging.rb:166:in `enter_level'
	from /home/alex/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/yard-0.8.7.6/lib/yard/parser/source_parser.rb:106:in `parse'
	from /home/alex/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/yard-0.8.7.6/lib/yard.rb:18:in `parse'
	from /home/alex/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/yard-0.8.7.6/lib/yard/cli/yardoc.rb:249:in `run'
	from /home/alex/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/yard-0.8.7.6/lib/yard/cli/command.rb:13:in `run'
	from /home/alex/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/yard-0.8.7.6/bin/yardoc:12:in `<top (required)>'
	from /home/alex/.rbenv/versions/2.2.2/bin/yardoc:23:in `load'
	from /home/alex/.rbenv/versions/2.2.2/bin/yardoc:23:in `<main>'
```

**Comment by lsegal** [comment] 2015-12-08 04:02
This was already identified as a bug in Ruby-- if it's recurring, you should really visit the Ruby issue tracker to raise it there, as it should have been resolved by [#10693](https://bugs.ruby-lang.org/issues/10693).

**Comment by aquach** [comment] 2015-12-08 04:03
Ah, yup, just saw https://bugs.ruby-lang.org/issues/11485 and followed it around. Thanks for your help!

**Comment by aquach** [comment] 2015-12-08 04:08
I believe this issue and #825 are separate bugs in the Ruby parser. Looks like the issue you linked has been addressed, but unfortunately https://bugs.ruby-lang.org/issues/11485 hasn't yet AFAICT. Thanks again!

**Comment by perlun** [comment] 2016-04-21 11:55
Maybe it would make sense to keep this one open, _even though_ it's not an issue in Yard per se. It makes it easier for people (like me) to find it when they run into it. :smile:

**Comment by lsegal** [comment] 2016-04-21 20:32
@perlun for management reasons we close issues that are already resolved or cannot be resolved in YARD's codebase. You should always search open and closed issues if you're looking for a specific problem. Finding a closed issue should let you know that it is no longer being actively researched for a root cause or patch. Hope that helps.

**Comment by perlun** [comment] 2016-04-25 05:38
Alright, thanks! No problems, I can understand that viewpoint.
