### ISSUE TITLE
Why first commented line get merged in source div?

### ISSUE THREAD

**Issue by benoittgt** [lsegal/yard#1313] opened 2020-03-03 09:56 UTC
Hello 

I have this type of code:
```ruby
      # @return [RSpec::Core::Reporter] the currently configured reporter
      def reporter
        # @reporter_buffer should only ever be set in this method to cover
        # initialization of @reporter.
```
[source](https://github.com/rspec/rspec-core/blob/3-9-maintenance/lib/rspec/core/configuration.rb#L1023-L1026)

But the problem is I get this result:

![Capture d’écran 2020-03-03 à 10 37 25](https://user-images.githubusercontent.com/8417720/75762528-2006ed80-5d3b-11ea-9870-fd1e1d51db55.png)

## Steps to reproduce

I did:

```ruby
module Foo
  # @api public
  # Foo doc
  def bar
    # comment line 1
    # comment line 2
  end
end
```

And no issue.

![Capture d’écran 2020-03-03 à 10 43 27](https://user-images.githubusercontent.com/8417720/75762972-d539a580-5d3b-11ea-9ee3-f5af223d2bd0.png)

On `rspec-core`

If I do:

```diff
       # @return [RSpec::Core::Reporter] the currently configured reporter
       def reporter
+
         # @reporter_buffer should only ever be set in this method to cover
```
The line is properly returned.

![Capture d’écran 2020-03-03 à 10 47 57](https://user-images.githubusercontent.com/8417720/75763390-79bbe780-5d3c-11ea-91ed-7362bf8ee808.png)

I made a very light copy of `rspec-core` with most of the files removed.

1. `git clone https://github.com/benoittgt/rspec-core/tree/only-configuration-reporter && cd rspec-core && git checkout only-configuration-reporter && export USE_GIT_REPOS=1 && bundle`
2. `bundle exec yard && yard server --reload`
3. http://localhost:8808/docs/RSpec/Core/Configuration#reporter-instance_method click on "source"

## Actual Output

![Capture d’écran 2020-03-03 à 10 37 25](https://user-images.githubusercontent.com/8417720/75762528-2006ed80-5d3b-11ea-9870-fd1e1d51db55.png)

## Expected Output

Carriage return after first comment.

## Environment details:

* OS: mac os
* Ruby version (`ruby -v`): 2.7
* YARD version (`yard -v`): 0.9.24
* Relevant software dependency/versions:
  * redcarpet (3.5.0)

I have read the [Contributing Guide][contrib].

[contrib]: https://github.com/lsegal/yard/blob/master/CONTRIBUTING.md

**Comment by lsegal** [comment] 2020-03-03 23:02
Seems like a weird bug where we are attaching the doc line to the method instead of the internal block.

**Comment by benoittgt** [comment] 2020-03-05 10:04
Interesting answer from @MSP-Greg https://github.com/rspec/rspec.github.io/pull/131#issuecomment-594341531

> Saw your issue in YARD, and ended up here. The problem above with RSpec::Core::Formatters can be solved by adding a blank line below the first line:
> 
> `RSpec::Support.require_rspec_support "directory_maker"`
> 
> Really, the comment for the RSpec::Core::Formatters module needs a blank line above it. I've only seen this with module/class comments, not method or constant comments.
> 
> I think it's a little different than the YARD issue, as the above code line isn't parsed by YARD.
> 
> JFYI, for a long time, everything was stable. Then RDoc switched from using their own Ruby parser to Ripper, and small changes have been made to Ripper (which really didn't care about comments) that have resulted in small breakages to YARD based doc systems...

In the meantime I made a smaller repo to reproduce the behavior https://github.com/benoittgt/rspec-core/tree/only-configuration-reporter

**Comment by benoittgt** [comment] 2020-03-05 15:00
Ok I do no have the issue on Ruby version below 2.7.

2.8

![Capture d’écran 2020-03-05 à 15 56 19](https://user-images.githubusercontent.com/8417720/75993664-1d062b80-5efa-11ea-89c9-aa5d91c269e9.png)

2.7

![Capture d’écran 2020-03-05 à 15 25 29](https://user-images.githubusercontent.com/8417720/75993679-242d3980-5efa-11ea-8fde-b6f03de1f5d2.png)

2.6.3
![Capture d’écran 2020-03-05 à 15 24 08](https://user-images.githubusercontent.com/8417720/75993711-3313ec00-5efa-11ea-8b17-7d35bf3e0447.png)

2.5.5
![Capture d’écran 2020-03-05 à 15 21 25](https://user-images.githubusercontent.com/8417720/75993721-36a77300-5efa-11ea-8474-165eb108d4c9.png)

2.4.0
![Capture d’écran 2020-03-05 à 15 18 49](https://user-images.githubusercontent.com/8417720/75993747-40c97180-5efa-11ea-9111-03d4045e146f.png)

Same with 2.2 and 2.1

**Comment by benoittgt** [comment] 2020-03-05 17:37
With a basic:

```ruby
class Configuration
  def reporter
    # @reporter_buffer should only ever be set in this method to cover
  end
end
```

I get in `html_syntax_highlight_ruby_ripper` with Ruby 2.6:
```ruby
#<YARD::Parser::Ruby::TokenResolver:0x00007ff7479acb58
 @default_namespace=#<yardoc method Configuration#reporter>,
 @tokens=
  [[:kw, "def", [1, 0]],
   [:sp, " ", [1, 3]],
   [:ident, "reporter", [1, 4]],
   [:nl, "\n", [1, 12]],
   [:sp, "  ", [2, 13]],
   [:comment,
    "# @reporter_buffer should only ever be set in this method to cover\n",
    [2, 15]],
   [:kw, "end", [3, 82]]]>
```
and
```html
"<span class='kw'>def</span> <span class='id identifier rubyid_reporter'>reporter</span>\n" +
"  <span class='comment'># @reporter_buffer should only ever be set in this method to cover\n" +
"</span><span class='kw'>end</span>"
```

With Ruby 2.7:
```ruby
#<YARD::Parser::Ruby::TokenResolver:0x00007fcf2c1040c0
 @default_namespace=#<yardoc method Configuration#reporter>,
 @tokens=
  [[:kw, "def", [1, 0]],
   [:sp, " ", [1, 3]],
   [:ident, "reporter", [1, 4]],
   [:sp, "  ", [2, 12]],
   [:comment,
    "# @reporter_buffer should only ever be set in this method to cover\n",
    [2, 14]],
   [:nl, "\n", [1, 81]],
   [:kw, "end", [3, 82]]]>
```
and
```html

"<span class='kw'>def</span> <span class='id identifier rubyid_reporter'>reporter</span>  <span class='comment'># @reporter_buffer should only ever be set in this method to cover\n" +
"</span>\n" +
"<span class='kw'>end</span>"
```

I seems there is a weird behavior with `[:nl, "\n",...` they are in different position. I will continue to investigate.

**Comment by lsegal** [comment] 2020-03-05 21:34
This looks like a straight up Ripper bug to me. Consider the following minimal reproduction:

```ruby
require 'pp'
require 'ripper'

SOURCE = "def name\n  # comment\nend"

class RipperParser < Ripper
  attr_accessor :tokens

  SCANNER_EVENTS.each do |event|
    define_method("on_#{event}") do |*args|
      puts "TOKEN:     #{event}"
      (@tokens ||= []) << [event, args]
      super(*args)
    end
  end
end

parser = RipperParser.new(SOURCE, '(stdin)')

puts "PARSING:"
parser.parse

puts "\nTOKENS:"
pp parser.tokens

puts "\nRIPPER SAYS"
pp Ripper.lex(SOURCE)
```

Which produces the following:

```
PARSING:
TOKEN:     kw
TOKEN:     sp
TOKEN:     ident
TOKEN:     sp
TOKEN:     comment
TOKEN:     nl
TOKEN:     kw

TOKENS:
[[:kw, ["def"]],
 [:sp, [" "]],
 [:ident, ["name"]],
 [:sp, ["  "]],
 [:comment, ["# comment\n"]],
 [:nl, ["\n"]],
 [:kw, ["end"]]]

RIPPER SAYS
[[[1, 0], :on_kw, "def", FNAME],
 [[1, 3], :on_sp, " ", FNAME],
 [[1, 4], :on_ident, "name", ENDFN],
 [[1, 8], :on_nl, "\n", BEG],
 [[2, 0], :on_sp, "  ", ENDFN],
 [[2, 2], :on_comment, "# comment\n", ENDFN],
 [[3, 0], :on_kw, "end", END]]
```

Note that "comment" is detected before "nl" in both the event and the collected tokens, which is different from the results in `Ripper.lex`. Unfortunately we don't rely on Ripper.lex, but the underlying `on_*` event parsing API that Ripper has. We could move this but this likely is causing parsing issues in other parts of YARD.

You may want to open an issue against Ruby-core about this, since the behavior has seemed to have regressed in 2.7.x.

**Comment by benoittgt** [comment] 2020-03-05 23:46
The source code of added functionality to Ripper is pretty obscure at first sight 😳. I dig into but didn't see a lot of difference expect maybe in `insert_comments`.

Outside of Yard, I checked the diff between 2.6.3 and 2.7 with Ripper using this:

```ruby
require 'ripper'
require 'yard'
require 'pp'
puts ">> RUBY_VERSION: #{RUBY_VERSION}"

ruby_code = <<-RUBY
def reporter
  # comment
end
RUBY

File.open("#{RUBY_VERSION.tr('.','-')}_ripper_lex.txt","w") do |f|
  PP.pp(Ripper.lex(ruby_code),f)
end
```

Diff between `2.6.3` et `2.7`:
![Capture d’écran 2020-03-06 à 00 31 48](https://user-images.githubusercontent.com/8417720/76035527-fc61c400-5f41-11ea-98d9-8ddf0160d723.png)

Their is no order difference in the array like I have in `YARD::Parser::Ruby::TokenResolver` on the previous comment so maybe the issue is in `insert_comments`? 

I do not see errors in how `nl` (new line) are handled. Next episode tomorrow.

**Comment by benoittgt** [comment] 2020-03-06 00:04
Done: https://redmine.ruby-lang.org/issues/16675

**Comment by lsegal** [comment] 2020-03-06 00:07
Thanks!

**Comment by benoittgt** [comment] 2020-03-06 08:11
Nobu say it is not an issue an close the ticket:

> This is because comment lines can be placed between fluent dot.
> That means it is undecidable if a newline before a comment line is ignored until comment lines end.

**Comment by lsegal** [comment] 2020-03-07 23:03
Fixed via above commit we can workaround this for tokenization since this does not affect the general parsing logic.

**Closed** 2020-03-07 23:03 UTC
Labels: Bug

**Comment by benoittgt** [comment] 2020-03-08 08:37
Well done @lsegal !
Thanks a lot 🙏
