### ISSUE TITLE
Keyword arguments with a Hash causes a crash

### ISSUE THREAD

**Issue by Damien43** [lsegal/yard#832] opened 2015-01-15 05:04 UTC
Hello
Sorry didnt give more details, I speak English with difficulty.

Given an example:

```shell
cat >test.rb && yardoc --verbose --debug --backtrace ./test.rb
def some_method(param: 'foo')
  param
end
D^
[debug]: Parsing ["./test.rb"] with `ruby` parser
[debug]: Parsing test.rb
/home/damien/.gem/ruby/2.2.0/gems/yard-0.8.7.6/lib/yard/parser/ruby/ruby_parser.rb:460:in `block (2 levels) in on_params': undefined method `type' for 48040:Fixnum (NoMethodError)
        from /home/damien/.gem/ruby/2.2.0/gems/yard-0.8.7.6/lib/yard/parser/ruby/ruby_parser.rb:458:in `map!'
        from /home/damien/.gem/ruby/2.2.0/gems/yard-0.8.7.6/lib/yard/parser/ruby/ruby_parser.rb:458:in `block in on_params'
        from /home/damien/.gem/ruby/2.2.0/gems/yard-0.8.7.6/lib/yard/parser/ruby/ruby_parser.rb:454:in `map!'
        from /home/damien/.gem/ruby/2.2.0/gems/yard-0.8.7.6/lib/yard/parser/ruby/ruby_parser.rb:454:in `on_params'
        from /home/damien/.gem/ruby/2.2.0/gems/yard-0.8.7.6/lib/yard/parser/ruby/ruby_parser.rb:50:in `parse'
        from /home/damien/.gem/ruby/2.2.0/gems/yard-0.8.7.6/lib/yard/parser/ruby/ruby_parser.rb:50:in `parse'
        from /home/damien/.gem/ruby/2.2.0/gems/yard-0.8.7.6/lib/yard/parser/ruby/ruby_parser.rb:15:in `parse'
        from /home/damien/.gem/ruby/2.2.0/gems/yard-0.8.7.6/lib/yard/parser/source_parser.rb:439:in `parse'
        from /home/damien/.gem/ruby/2.2.0/gems/yard-0.8.7.6/lib/yard/parser/source_parser.rb:44:in `block in parse'
        from /home/damien/.gem/ruby/2.2.0/gems/yard-0.8.7.6/lib/yard/logging.rb:70:in `capture'
        from /home/damien/.gem/ruby/2.2.0/gems/yard-0.8.7.6/lib/yard/parser/source_parser.rb:43:in `parse'
        from /home/damien/.gem/ruby/2.2.0/gems/yard-0.8.7.6/lib/yard/parser/source_parser.rb:368:in `parse_in_order'
        from /home/damien/.gem/ruby/2.2.0/gems/yard-0.8.7.6/lib/yard/parser/source_parser.rb:107:in `block in parse'
        from /home/damien/.gem/ruby/2.2.0/gems/yard-0.8.7.6/lib/yard/logging.rb:166:in `enter_level'
        from /home/damien/.gem/ruby/2.2.0/gems/yard-0.8.7.6/lib/yard/parser/source_parser.rb:106:in `parse'
        from /home/damien/.gem/ruby/2.2.0/gems/yard-0.8.7.6/lib/yard.rb:18:in `parse'
        from /home/damien/.gem/ruby/2.2.0/gems/yard-0.8.7.6/lib/yard/cli/yardoc.rb:249:in `run'
        from /home/damien/.gem/ruby/2.2.0/gems/yard-0.8.7.6/lib/yard/cli/command.rb:13:in `run'
        from /home/damien/.gem/ruby/2.2.0/gems/yard-0.8.7.6/bin/yardoc:12:in `<top (required)>'
        from /home/damien/.gem/ruby/2.2.0/bin/yardoc:23:in `load'
        from /home/damien/.gem/ruby/2.2.0/bin/yardoc:23:in `<main>'
```

**Comment by lsegal** [comment] 2015-01-15 05:20
This is a duplicate of #825

**Closed by lsegal** 2015-01-15 05:20 UTC
