### ISSUE TITLE
Issues with annotate and the overview

### ISSUE THREAD

**Issue by bakku** [lsegal/yard#1038] opened 2016-11-19 14:07 UTC
## Steps to reproduce

This is the minimal reproduction for the issue. I've done my best to remove
all extraneous code and unique environment state on my machine before providing
these steps:

1. Put a top level comment above the schema information of annotate for the overview
2. Run yard
3. View the docs in the browser. Everything is fine. Overview and schema information exists
4. Run annotate
5. Run yard again

## Actual Output

Schema information of annotate is being ignored. Overview is the same as before.
In the code the Schema Information of annotate is now placed above the old top level comment (annotate is responsible for this)

## Expected Output

Schema information updates with annotate but after running yard still both the overview and schema information is being shown.

## Environment details:

* OS: macOS Sierra
* Ruby version (`ruby -v`): 2.3.1
* YARD version (`yard -v`): 0.9.5
* Relevant software dependency/versions:
  * annotate v2.6.10

I have read the [Contributing Guide][contrib].

**Comment by lsegal** [comment] 2016-11-21 18:22
Can you explain what you mean by "schema information of annotate is being ignored"? I can't seem to reproduce anything that I would consider out of place. If your report is regarding the line of space between the `== Schema Information` block and the manually entered doc string, then that is a behavior of `annotate`, not YARD. There's nothing YARD can do about this one.

If we are indeed talking about the same thing, you should open an issue with annotate to work with existing docstrings. YARD does not show disconnected docstring blocks as a single docstring, i.e., an empty line separating two comments will be treated as two distinct documentation blocks. This would be a third party issue.

**Comment by bakku** [comment] 2016-11-23 09:51
Thanks for your answer.

Simply spoken, I would like to be able to use annotate as well as yard without the both of them interfering with each other. It seems that yard expects the `OVERVIEW` to generate the docs as a top level comment.

So whenever I run `annotate` AFTER having added a top level comment then the top level comment is placed below the `== Schema Information`. This would be perfectly fine with me, the only problem I have is that with this structure of the document, yard does not display the `== Schema Information` part anymore in its generated docs.

The structure of the Ruby class which I want to document is not that important to me. The generated docs are which matters. I hope I could explain my point a bit clearer this time :)

**Comment by lsegal** [comment] 2016-12-27 18:22
> It seems that yard expects the OVERVIEW to generate the docs as a top level comment.

YARD's only expectation is that the last comment block prior to your class definition is the docstring:

```ruby
# Docstring here
class Foo; end
```

If you have *two* distinct comment blocks, YARD will only take the one closest to the definition:

```ruby
# Comment here

# Docstring here
class Foo; end
```

This is a feature of YARD and unlikely to change. Annotate has to be updated to avoid placing a space between the two blocks. Separating these two blocks with an empty line forces YARD (and all other doc tools) to treat these as two distinct comment blocks. If you want both docstrings to be combined, they need to be a single block:

```ruby
# == Schema Information
#
# SCHEMA INFO HERE
#
# OVERVIEW HERE
class Foo; end
```

Note the lack of empty newline between the docstrings. You should open an issue with annotate to have this behavior. YARD is not the only doc tool that will ignore the schema info if not generated in this way.

I'm marking this as closed because it's a third-party issue, but thanks for bringing this to our attention!

**Closed by lsegal** 2016-12-27 18:22 UTC
Labels: Needs Feedback, ThirdParty
