### ISSUE TITLE
`html_markup_rdoc': undefined method `new' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by georgemillo** [lsegal/yard#816] opened 2014-12-04 15:41 UTC
Trying to run `yardoc` with the following `yardopts` file:

    --markup markdown
    --markup-provider kramdown
    --no-private

Gives me the following error:

    /Users/george/.rvm/gems/ruby-2.1.5/gems/yard-0.8.7.6/lib/yard/templates/helpers/html_helper.rb:101:in `html_markup_rdoc': undefined method `new' for nil:NilClass (NoMethodError)
    from /Users/george/.rvm/gems/ruby-2.1.5/gems/yard-0.8.7.6/lib/yard/templates/helpers/html_helper.rb:41:in `htmlify'
    from /Users/george/.rvm/gems/ruby-2.1.5/gems/yard-0.8.7.6/templates/default/layout/html/setup.rb:49:in `diskfile'
    from /Users/george/.rvm/gems/ruby-2.1.5/gems/yard-0.8.7.6/lib/yard/templates/template.rb:355:in `render_section'
    from /Users/george/.rvm/gems/ruby-2.1.5/gems/yard-0.8.7.6/lib/yard/templates/template.rb:251:in `block (2 levels) in run'
    from /Users/george/.rvm/gems/ruby-2.1.5/gems/yard-0.8.7.6/lib/yard/templates/template.rb:248:in `each'
    from /Users/george/.rvm/gems/ruby-2.1.5/gems/yard-0.8.7.6/lib/yard/templates/template.rb:248:in `block in run'
    from /Users/george/.rvm/gems/ruby-2.1.5/gems/yard-0.8.7.6/lib/yard/templates/template.rb:386:in `add_options'
    from /Users/george/.rvm/gems/ruby-2.1.5/gems/yard-0.8.7.6/lib/yard/templates/template.rb:247:in `run'
    from /Users/george/.rvm/gems/ruby-2.1.5/gems/yard-0.8.7.6/lib/yard/templates/template.rb:269:in `block in yieldall'
    from /Users/george/.rvm/gems/ruby-2.1.5/gems/yard-0.8.7.6/lib/yard/templates/template.rb:400:in `with_section'
    from /Users/george/.rvm/gems/ruby-2.1.5/gems/yard-0.8.7.6/lib/yard/templates/template.rb:269:in `yieldall'
    from /Users/george/.rvm/gems/ruby-2.1.5/gems/yard-0.8.7.6/templates/default/layout/html/layout.erb:18:in `_erb_cache_5'
    from /Users/george/.rvm/gems/ruby-2.1.5/gems/yard-0.8.7.6/lib/yard/templates/template.rb:279:in `erb'
    from /Users/george/.rvm/gems/ruby-2.1.5/gems/yard-0.8.7.6/lib/yard/templates/template.rb:357:in `render_section'
    from /Users/george/.rvm/gems/ruby-2.1.5/gems/yard-0.8.7.6/lib/yard/templates/template.rb:251:in `block (2 levels) in run'
    from /Users/george/.rvm/gems/ruby-2.1.5/gems/yard-0.8.7.6/lib/yard/templates/template.rb:248:in `each'
    from /Users/george/.rvm/gems/ruby-2.1.5/gems/yard-0.8.7.6/lib/yard/templates/template.rb:248:in `block in run'
    from /Users/george/.rvm/gems/ruby-2.1.5/gems/yard-0.8.7.6/lib/yard/templates/template.rb:386:in `add_options'
    from /Users/george/.rvm/gems/ruby-2.1.5/gems/yard-0.8.7.6/lib/yard/templates/template.rb:247:in `run'
    from /Users/george/.rvm/gems/ruby-2.1.5/gems/yard-0.8.7.6/lib/yard/templates/template.rb:135:in `run'
    from /Users/george/.rvm/gems/ruby-2.1.5/gems/yard-0.8.7.6/templates/default/fulldoc/html/setup.rb:51:in `block in serialize_index'
    from /Users/george/.rvm/gems/ruby-2.1.5/gems/yard-0.8.7.6/lib/yard/templates/engine.rb:122:in `block in with_serializer'
    from /Users/george/.rvm/gems/ruby-2.1.5/gems/yard-0.8.7.6/lib/yard/logging.rb:70:in `capture'
    from /Users/george/.rvm/gems/ruby-2.1.5/gems/yard-0.8.7.6/lib/yard/templates/engine.rb:120:in `with_serializer'
    from /Users/george/.rvm/gems/ruby-2.1.5/gems/yard-0.8.7.6/templates/default/fulldoc/html/setup.rb:50:in `serialize_index'
    from /Users/george/.rvm/gems/ruby-2.1.5/gems/yard-0.8.7.6/templates/default/fulldoc/html/setup.rb:67:in `serialize_file'
    from /Users/george/.rvm/gems/ruby-2.1.5/gems/yard-0.8.7.6/templates/default/fulldoc/html/setup.rb:10:in `block in init'
    from /Users/george/.rvm/gems/ruby-2.1.5/gems/yard-0.8.7.6/templates/default/fulldoc/html/setup.rb:9:in `each'
    from /Users/george/.rvm/gems/ruby-2.1.5/gems/yard-0.8.7.6/templates/default/fulldoc/html/setup.rb:9:in `each_with_index'
    from /Users/george/.rvm/gems/ruby-2.1.5/gems/yard-0.8.7.6/templates/default/fulldoc/html/setup.rb:9:in `init'
    from /Users/george/.rvm/gems/ruby-2.1.5/gems/yard-0.8.7.6/lib/yard/templates/template.rb:185:in `initialize'
    from /Users/george/.rvm/gems/ruby-2.1.5/gems/yard-0.8.7.6/lib/yard/templates/template.rb:130:in `new'
    from /Users/george/.rvm/gems/ruby-2.1.5/gems/yard-0.8.7.6/lib/yard/templates/template.rb:135:in `run'
    from /Users/george/.rvm/gems/ruby-2.1.5/gems/yard-0.8.7.6/lib/yard/templates/engine.rb:104:in `generate'
    from /Users/george/.rvm/gems/ruby-2.1.5/gems/yard-0.8.7.6/lib/yard/cli/yardoc.rb:339:in `run_generate'
    from /Users/george/.rvm/gems/ruby-2.1.5/gems/yard-0.8.7.6/lib/yard/cli/yardoc.rb:253:in `run'
    from /Users/george/.rvm/gems/ruby-2.1.5/gems/yard-0.8.7.6/lib/yard/cli/command.rb:13:in `run'
    from /Users/george/.rvm/gems/ruby-2.1.5/gems/yard-0.8.7.6/lib/yard/cli/command_parser.rb:71:in `run'
    from /Users/george/.rvm/gems/ruby-2.1.5/gems/yard-0.8.7.6/lib/yard/cli/command_parser.rb:53:in `run'
    from /Users/george/.rvm/gems/ruby-2.1.5/gems/yard-0.8.7.6/bin/yard:12:in `<top (required)>'
    from /Users/george/.rvm/gems/ruby-2.1.5/bin/yard:23:in `load'
    from /Users/george/.rvm/gems/ruby-2.1.5/bin/yard:23:in `<main>'
    from /Users/george/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `eval'
    from /Users/george/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `<main>'

The offending line in `html_helper` is:

      doc = markup_class(:rdoc).new(text)

`markup_class(:rdoc)` is returning `nil` when it should be returning.... `Kramdown::Document`, maybe? Here's the method in full.

      def markup_class(type = options.markup)
        load_markup_provider(type)
        MarkupHelper.markup_cache[type][:class]
      end

If I add `puts MarkupHelper.markup_cache` I can see it current equals `{:rdoc=>{}, :markdown=>{:provider=>:kramdown, :class=>Kramdown::Document}}` - i.e. `rdoc` is just an empty hash, thus the error.

Is this a bug, or am I misunderstanding how to use Yard? I'm trying to use markdown with kramdown as per the instructions in the [README of the annotate_models gem](https://github.com/ctran/annotate_models/blob/v2.6.5/README.rdoc).

**Comment by leoc** [comment] 2016-05-06 06:28
I am having the same problem. Where you able to resolve this issue?

rdoc (4.2.2)
yard (0.8.7.6)

.yardopts:
```
--markup markdown
--markup-provider kramdown
--charset UTF-8
```

Shouldn't Yard use markdown instead of rdoc?

**Comment by lsegal** [comment] 2016-05-06 06:37
> Shouldn't Yard use markdown instead of rdoc, though?

@leoc the backtrace indicates that YARD is parsing an explicit rdoc file, presumably a file with a `.rdoc` extension.

Can you provide a set of reliable reproduction steps for this?

**Comment by leoc** [comment] 2016-05-06 06:43
Whoops! Indeed I had a *.rdoc file somewhere deep down my docs folder! Converting that to Markdown fixed my issue. Thank you!

**Comment by lsegal** [comment] 2016-07-06 03:37
Marking this as closed since there is no reproduction. It would be great to have one in order to re-open and fix this (other than switching to markdown).

**Closed by lsegal** 2016-07-06 03:37 UTC
