### ISSUE TITLE
ruby_parser.rb:212:in `on_ignored_nl': undefined method `length' for nil:NilClass

### ISSUE THREAD

**Issue by mattparlane** [lsegal/yard#979] opened 2016-07-11 23:17 UTC
Firstly, congrats on 0.9.0! Thanks for your hard work.

`nano test-yard.rb`

```
url = url
  .strip # strip
  .downcase
```

`yard doc test-yard.rb`

```
/usr/local/lib/ruby/gems/2.3.0/gems/yard-0.9.0/lib/yard/parser/ruby/ruby_parser.rb:212:in `on_ignored_nl': undefined method `length' for nil:NilClass (NoMethodError)
	from /usr/local/lib/ruby/gems/2.3.0/gems/yard-0.9.0/lib/yard/parser/ruby/ruby_parser.rb:51:in `parse'
	from /usr/local/lib/ruby/gems/2.3.0/gems/yard-0.9.0/lib/yard/parser/ruby/ruby_parser.rb:51:in `parse'
	from /usr/local/lib/ruby/gems/2.3.0/gems/yard-0.9.0/lib/yard/parser/ruby/ruby_parser.rb:15:in `parse'
	from /usr/local/lib/ruby/gems/2.3.0/gems/yard-0.9.0/lib/yard/parser/source_parser.rb:439:in `parse'
	from /usr/local/lib/ruby/gems/2.3.0/gems/yard-0.9.0/lib/yard/parser/source_parser.rb:44:in `block in parse'
	from /usr/local/lib/ruby/gems/2.3.0/gems/yard-0.9.0/lib/yard/logging.rb:70:in `capture'
	from /usr/local/lib/ruby/gems/2.3.0/gems/yard-0.9.0/lib/yard/parser/source_parser.rb:43:in `parse'
	from /usr/local/lib/ruby/gems/2.3.0/gems/yard-0.9.0/lib/yard/parser/source_parser.rb:368:in `parse_in_order'
	from /usr/local/lib/ruby/gems/2.3.0/gems/yard-0.9.0/lib/yard/parser/source_parser.rb:111:in `block in parse'
	from /usr/local/lib/ruby/gems/2.3.0/gems/yard-0.9.0/lib/yard/logging.rb:166:in `enter_level'
	from /usr/local/lib/ruby/gems/2.3.0/gems/yard-0.9.0/lib/yard/parser/source_parser.rb:110:in `parse'
	from /usr/local/lib/ruby/gems/2.3.0/gems/yard-0.9.0/lib/yard.rb:18:in `parse'
	from /usr/local/lib/ruby/gems/2.3.0/gems/yard-0.9.0/lib/yard/cli/yardoc.rb:249:in `run'
	from /usr/local/lib/ruby/gems/2.3.0/gems/yard-0.9.0/lib/yard/cli/command.rb:13:in `run'
	from /usr/local/lib/ruby/gems/2.3.0/gems/yard-0.9.0/lib/yard/cli/command_parser.rb:71:in `run'
	from /usr/local/lib/ruby/gems/2.3.0/gems/yard-0.9.0/lib/yard/cli/command_parser.rb:53:in `run'
	from /usr/local/lib/ruby/gems/2.3.0/gems/yard-0.9.0/bin/yard:12:in `<top (required)>'
	from /usr/local/bin/yard:23:in `load'
	from /usr/local/bin/yard:23:in `<main>'
```

**Comment by lsegal** [comment] 2016-07-12 00:02
This is a duplicate of #835, which is a Ruby bug. I would suggest following up on the Ruby tracker to help them prioritize this issue.

**Comment by mattparlane** [comment] 2016-07-12 00:05
Gotcha. Apologies, I only searched open issues, not closed ones.

**Comment by mattparlane** [comment] 2016-07-12 00:09
Sorry, I should have mentioned I'm running Ruby 2.3.1:

`ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-linux]`

Does that make any difference?

**Comment by lsegal** [comment] 2016-07-12 00:11
No-- the latter issue is still open and hasn't been resolved, it seems: https://bugs.ruby-lang.org/issues/11485

YARD could possibly work around this bug by handling the nil token. I'll take a look. Going to re-open this since it is affecting multiple users and Ruby core team seems to have forgotten about it.

**Closed** 2016-07-12 00:17 UTC

**Comment by lsegal** [comment] 2016-07-12 00:19
I just pushed a quick fix to handle this case.

**Comment by mattparlane** [comment] 2016-07-12 00:30
Nice work, just tested it manually and it works well. Thanks!
