### ISSUE TITLE
Server hangs with Ruby 2.4

### ISSUE THREAD

**Issue by MaxPleaner** [lsegal/yard#950] opened 2016-03-18 19:02 UTC
Not sure if this is really an issue you're concerned about, as Ruby 2.4 is still in development.

But the `yard server` command hangs with this version.

The command line shows the server starting up OK but connecting to `localhost:8808` never renders a HTML page. 

Feel free to close this issue if you'd rather test against standard Rubies only

**Comment by lsegal** [comment] 2016-03-19 18:58
I would recommend opening an issue against Ruby trunk about this since it could very well avoid a regression in Ruby 2.4: https://bugs.ruby-lang.org/issues

**Comment by lsegal** [comment] 2016-04-15 06:21
Closing since this is unlikely to be an issue with YARD. Please report compatibility issues with trunk Ruby versions against Ruby itself, since that is where the changes happened.

**Closed by lsegal** 2016-04-15 06:21 UTC
