### ISSUE TITLE
YARD erases certain non-ruby code blocks

### ISSUE THREAD

**Issue by kylekyle** [lsegal/yard#948] opened 2016-03-10 05:21 UTC
YARD assumes [code blocks that don't specify a language are ruby](https://github.com/lsegal/yard/blob/5a062a6/lib/yard/code_objects/base.rb#L224). The only problem is that the `RubyParser` that tokenizes ruby code for syntax highlighting chokes on certain non-ruby blocks. For instance,

```
 $ YARD will erase any block that starts with a space followed by a dollar sign
```

The best solution would be to assume that blocks that don't specify a language are plaintext. That's a five character change in the source code, but might cause markdown that assumes blocks are ruby by default to stop highlighting. 

The other solution would be to actually check if the code block is valid ruby. This is how I've monkey patched my doc server: 

```ruby
require 'parser/current'

class YARD::Parser::Ruby::RubyParser
  class << self
    alias :original :parse

    def parse source, filename
      Parser::CurrentRuby.parse source
      original source, filename
    rescue Parser::SyntaxError
      raise YARD::Parser::ParserSyntaxError
    end
  end
end
```

This is slow and hacky, but I didn't see a way to detect that the parser had choked without resorting to a proper syntax check.

**Comment by lsegal** [comment] 2016-04-16 01:27
I can't seem to reproduce this. YARD has always fallen back to displaying code as unhighlighted plaintext if the syntax parse attempt fails-- this logic is encoded right here:

https://github.com/lsegal/yard/blob/master/lib/yard/templates/helpers/html_syntax_highlight_helper.rb#L37

Furthermore, you can find examples of this working as intended in [YARD's own docs](http://www.rubydoc.info/gems/yard#Installing). 

Can you show how you are reproducing this issue?

**Comment by kylekyle** [comment] 2016-04-17 00:06
Here's the version of Ruby and YARD I'm running: 

```bash
$ ruby --version 
ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-darwin14]
$ yard --version
yard 0.8.7.6
```

Here's an example `README.md`

<pre>
The following block renders as ruby even though no language is specified:

```
def method
  puts "a method!"
end
```

```
 :~$ This text is always clobbered by the YARD parser
```

```
 $ This line is only clobbered in Ruby 1.9
```
</pre>

Running the `yardoc` utility against that `README.md` generates the following

> ![screenshot](https://cloud.githubusercontent.com/assets/226019/14584310/9bd6dad6-040e-11e6-87cf-4a659843a9f4.png)

**Comment by lsegal** [comment] 2016-04-17 00:27
I forgot to add: you can use the `plain` language type to force YARD to treat the block as plaintext:

    ```plain
    $ plain text here
    ```

Or via the !!!bang prefix in code blocks for non-Markdown files:

```
    !!!plain
    $ plain text here
```

As for the 2nd block in this specific issue, it looks like Ripper is in fact parsing it as valid Ruby code but omitting the rest of the line:

```
$ ruby -rripper -e "class X < Ripper; def on_parse_error(m) p m end end; X.parse ':$~ hello'"
"syntax error, unexpected tIDENTIFIER, expecting end-of-input"
$ ruby -rripper -e "class X < Ripper; def on_parse_error(m) p m end end; X.parse ':~$ hello'"

$ ruby -rripper -e 'p Ripper.tokenize ":~$ hello"'
[":", "~"]
```

As long as Ripper is telling YARD that it's valid Ruby, there's not much we can do about this. You should [file a bug against Ruby](http://bugs.ruby-lang.org) because Ripper should be raising a syntax error here. This would be a third-party issue.

As for the 3rd block in Ruby 1.9, which version are you specifically using? My guess is that there is a related Ripper bug in that specific version.

That said, you can work around these issues with the above `plain` suggestion. Hope that helps!

**Comment by kylekyle** [comment] 2016-04-17 01:15
Why not simply change [the default](https://github.com/lsegal/yard/blob/5a062a6/lib/yard/code_objects/base.rb#L224) for source blocks to plaintext? If we want to keep Ruby as the default for source blocks, then we need to verify the code block is valid Ruby before trying to generate an AST. 

> As long as Ripper is telling YARD that it's valid Ruby, there's not much we can do about this.

Ripper was designed to make it easy for users to access the AST for a Ruby program, not to diagnose whether source code is or is not Ruby. [Parser](https://github.com/whitequark/parser) is much better suited to that task. Since Ripper wasn't designed to diagnose code, I don't think filing a ticket against Ruby is the right answer. 

I understand if changing the default for source blocks changes the behavior of YARD too much. I would also understand if you didn't want to add [Parser](https://github.com/whitequark/parser) as a dependency. So maybe this is just something that you mark as "Won't Fix". I just wanted to document the issue.

**Comment by lsegal** [comment] 2016-04-17 01:32
> Why not simply change the default for source blocks to plaintext? 

Because this would be a huge breaking change for YARD (that would literally break every single user), but even without that obvious blocker, it is simply not an intended behavior. 

YARD is a documentation tool for Ruby, and so, it makes sense that "Ruby source" should be the sane default for this tool. From a UX perspective, it would be extremely verbose if I had to tell YARD that each code block in my documentation was Ruby code, because most of them will be (and those that aren't are transparently handled anyway). This would be a bad UX:

    ```ruby
    # I have to tell YARD that this is Ruby code
    def foo; end
    ```

I'm confident if implemented this way, YARD would receive many complaints and pull requests to make Ruby code the default; effectively reverting this proposal. Using code blocks to list non-Ruby source should be the exception, not the rule, and it should make sense to have to tell your doc tool when this happens. Fortunately you don't even have to tell the tool in 95%+ of cases, since there is auto-detection. Using something like `!!!plain` is reasonable in the edge cases where the auto-detection fails.

> If we want to keep Ruby as the default for source blocks, then we need to verify the code block is valid Ruby before trying to generate an AST.

That's what using Ripper's parser does.

> Ripper was designed to make it easy for users to access the AST for a Ruby program, not to diagnose whether source code is or is not Ruby. 

This is not accurate. Ripper is [directly and intentionally coupled to the parser](https://github.com/ruby/ruby/blob/trunk/parse.y#L616) and its intent is to provide the exact same feedback as parsing code directly. It's not a diagnostic tool, it is the parsing infrastructure abstraction in Ruby. There's no reason for a third-party dependency (that, by the way, could fail in the exact same way).

> I don't think filing a ticket against Ruby is the right answer.

It *is* objectively a bug for Ripper not to raise an `on_parse_error` event for a parse error if Ruby itself does. Ripper is by definition not behaving correctly if it is not emitting an event that should have been emitted. I'm not sure how you could argue that Ripper is behaving correctly, here. At the very least, I would definitely recommend filing the issue and letting maintainers be the judge of whether this can/should be fixed upstream.

**Comment by kylekyle** [comment] 2016-04-17 02:45
> There's no reason for a third-party dependency (that, by the way, could fail in the exact same way).

Unlikely. The [Parser gem](https://github.com/whitequark/parser) uses the [bison grammar from Ruby itself](http://whitequark.org/blog/2012/10/02/parsing-ruby/), so it will always produce the same parse result that Ruby would. It also has a single runtime dependency, [ast](https://github.com/whitequark/ast), which has no runtime dependencies. 

Adding a pass with Parser would let you keep Ruby as the default source and always generate valid AST. 

> At the very least, I would definitely recommend filing the issue and letting maintainers be the judge of whether this can/should be fixed upstream.

Sure.

**Comment by lsegal** [comment] 2016-04-17 03:10
> Unlikely. The Parser gem uses the bison grammar from Ruby itself, so it will always produce the same parse result that Ruby would.

You could make that same argument for Ripper, though, which is quite literally embedded in the same grammar file used by MRI (see above), and yet, still occasionally has bugs (as evidenced by this issue). There are also plenty of other issues with a third-party lib, like going stale when Ruby updates its own grammar.

I'm not saying Parser is a bad thing-- it's a great library. I'm just pointing out that using a third-party library doesn't mitigate this specific issue. This issue is due to a defect in Ripper-- any defect in Parser could lead to the same problem downstream. Parser could certainly end up having a regression too, no?

> Adding a pass with Parser would let you keep Ruby as the default source and always generate valid AST.

I'm not convinced that your assertion is guaranteed to be true in every case. And this is the point: Ripper will "always" generate a valid AST for valid Ruby-- this is what it is for. The caveat is of course that the library must be working correctly, but this caveat applies equally to any other library we take on. Parser *can* fail, too. It might be unlikely to fail, but it can.

I'm marking this as closed since YARD itself is working as intended and the bug lives upstream in Ripper. Changing the default source language is a breaking change / non-starter, and switching to Parser would also be a breaking change that also involves a ton of extra work (rewriting the entirety of the Ruby handler implementations) just to resolve this one issue. And finally, there is also a fairly simple workaround that resolves the issue in this one edge case (I can't reproduce the 1.9 issue in 1.9.3, so presumably this was another Ripper regression that had since been resolved, and upgrading your Ruby would be the solution here). 

Thank you for bringing this Ripper bug to light, though!

**Closed by lsegal** 2016-04-17 03:10 UTC
Labels: ThirdParty

**Comment by lsegal** [comment] 2016-04-17 19:48
FYI, reported here: https://bugs.ruby-lang.org/issues/12295

**Comment by kylekyle** [comment] 2016-08-04 12:10
I think we've established that this is a bug in Ripper. But since Ripper has rejected and closed the issue, can we at least apply a work-around in YARD?

**Comment by lsegal** [comment] 2016-08-07 21:05
Thanks for following up on the response. Done!
