### ISSUE TITLE
Fails to generate documentation for Ruby 2.2.3 core

### ISSUE THREAD

**Issue by olistik** [lsegal/yard#895] opened 2015-08-24 13:37 UTC
Here's my environment:

```
ಠ_ಠ ruby -v
ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-darwin14]
ಠ_ಠ uname -a
Darwin titan.local 14.5.0 Darwin Kernel Version 14.5.0: Wed Jul 29 02:26:53 PDT 2015; root:xnu-2782.40.9~1/RELEASE_X86_64 x86_64
ಠ_ಠ rvm -v
rvm 1.26.11 (latest) by Wayne E. Seguin <wayneeseguin@gmail.com>, Michal Papis <mpapis@gmail.com> [https://rvm.io/]
ಠ_ಠ yard --version
yard 0.8.7.6
```

and here's the [gist](https://gist.github.com/olistik/c8b59585ffd8ff468be7) with the steps that reproduce the bug:

```
ಠ_ಠ wget https://cache.ruby-lang.org/pub/ruby/2.2/ruby-2.2.3.tar.bz2
ಠ_ಠ tar xvfj ruby-2.2.3.tar.bz2
ಠ_ಠ cd ruby-2.2.3
ಠ_ಠ yardoc --debug *.c
# ...
[error]: Exception occurred while generating 'IO.html'
[error]: NoMethodError: undefined method `length' for nil:NilClass
[error]: Stack trace:
	/Users/olistik/.rvm/gems/ruby-2.2.2/gems/yard-0.8.7.6/lib/yard/parser/ruby/ruby_parser.rb:210:in `on_ignored_nl'
	/Users/olistik/.rvm/gems/ruby-2.2.2/gems/yard-0.8.7.6/lib/yard/parser/ruby/ruby_parser.rb:50:in `parse'
	/Users/olistik/.rvm/gems/ruby-2.2.2/gems/yard-0.8.7.6/lib/yard/parser/ruby/ruby_parser.rb:50:in `parse'
	/Users/olistik/.rvm/gems/ruby-2.2.2/gems/yard-0.8.7.6/lib/yard/parser/ruby/ruby_parser.rb:15:in `parse'
	/Users/olistik/.rvm/gems/ruby-2.2.2/gems/yard-0.8.7.6/lib/yard/parser/base.rb:18:in `parse'
	/Users/olistik/.rvm/gems/ruby-2.2.2/gems/yard-0.8.7.6/lib/yard/templates/helpers/html_syntax_highlight_helper.rb:20:in `html_syntax_highlight_ruby_ripper'

[debug]: Serializing to doc/IO/EAGAINWaitReadable.html
[debug]: Serializing to doc/IO/EAGAINWaitWritable.html
[debug]: Serializing to doc/IO/EWOULDBLOCKWaitReadable.html
[debug]: Serializing to doc/IO/EWOULDBLOCKWaitWritable.html
[debug]: Serializing to doc/IO/EINPROGRESSWaitReadable.html
[debug]: Serializing to doc/IO/EINPROGRESSWaitWritable.html
[debug]: Serializing to doc/File.html
[debug]: Serializing to doc/Complex/compatible.html
Files:          47
Modules:        17 (   10 undocumented)
Classes:       104 (   20 undocumented)
Constants:     118 (   23 undocumented)
Methods:      1665 (   36 undocumented)
 95.33% documented
ಠ_ಠ
```

**Comment by lsegal** [comment] 2015-08-24 18:25
This may be a regression in Ruby. It looks like Ripper has started emitting an `on_ignored_nl` event with `[nil]` as the parameter, which I'm not sure it should be doing. The `on_ignored_nl` method should be called with the token as a parameter, and I'm not sure why a token would ever be nil. I will open an issue with Ruby to confirm if this is expected or not.

**Comment by lsegal** [comment] 2015-08-24 19:36
Ruby bug reported here: https://bugs.ruby-lang.org/issues/11485

**Comment by olistik** [comment] 2015-08-25 08:56
@lsegal you're the man :-) Thanks for your efforts :-)

**Comment by lsegal** [comment] 2015-10-19 22:32
I'm going to close this as a third-party issue since it seems as though this is a Ripper issue. Doesn't look like there's been any movement on the issue in the last two months on Ruby's side, so you might want to follow up and ping them if you're still running into this issue. Sorry I can't be more helpful on this!

**Closed by lsegal** 2015-10-19 22:32 UTC

**Comment by olistik** [comment] 2015-10-20 07:12
Thanks again, I'm just sorry that it looks like a Yard's fault at first sight.
