### ISSUE TITLE
Parsing %i in constant definition

### ISSUE THREAD

**Issue by davidsoncasey** [lsegal/yard#1006] opened 2016-08-04 22:54 UTC
When using Yard on a class that has a constant declared with `%i`, the constant does not include the `%i` when viewing the generated documentation.

## Steps to reproduce
Create a class such as
```ruby
class Foo
  FOO = %i(foo, bar)
end
```
When viewing the documentation for this class, the constant FOO appears does not include the initial `%i(` characters.

## Actual Output
I'm not familiar with the parser, but borrowing from the Ruby parser specs:
```ruby
> src = "%i(\na b c\n d e f\n)"
> p = YARD::Parser::Ruby::RubyParser.new(src, nil).parse.root.first
> p.jump(:qwords_literal).source
=> "a b c\n d e f"
```
leaving the `%i` out

## Expected Output
A similar example using `%w`:
```ruby
> src = "%i(\na b c\n d e f\n)"
> p = YARD::Parser::Ruby::RubyParser.new(src, nil).parse.root.first
> p.jump(:qwords_literal).source
=> "%w(\na b c\n d e f\n)"
```

Thank you! I've written some specs that replicate the issue and could put together a PR if you like.

## Environment details:

* OS: OS X 10.11.6
* Ruby version (`ruby -v`):  2.3.0
* YARD version (`yard -v`): 0.8.7.6

I have read the [Contributing Guide][contrib].

[contrib]: https://github.com/lsegal/yard/blob/master/CONTRIBUTING.md

**Comment by MSP-Greg** [comment] 2016-08-05 23:44
I believe the issue is that
`:qwords_literal => :qwords_beg` is mapped, but
`:qsymbols_literal => :qsymbols_beg` is not.

I can also pull together a PR, I've got it working on my system with 0.9.5

**Comment by davidsoncasey** [comment] 2016-08-05 23:55
@MSP-Greg if you've got it working, it would be great if you put together a PR. I'm not familiar with the project so it would probably take me a while to get it figured out. Thanks for the quick response on that!

**Comment by MSP-Greg** [comment] 2016-08-06 01:41
@davidsoncasey per my last comment, I've got the 'parsing' working thru to the html.

The %w array is all green, which I assume you're also seeing.  I'd prefer the %i array to be the 'reddish symbol color', but I haven't got that sorted out.  When I do, I'll do a PR.

**Comment by MSP-Greg** [comment] 2016-08-07 03:10
@davidsoncasey just an update, of the four (%w %W %i %I), only %w shows 'expected' output.

So, a bit more than we originally thought.

**Comment by lsegal** [comment] 2016-08-07 03:17
Feel free to open this as a PR.

**Comment by MSP-Greg** [comment] 2016-08-07 18:26
Well, I've found two ways to fix this, so I thought I ask you, as parsers are something that I'm learning about very quickly, but I'm by no means an expert.  Nor have I looked to see if and where `RipperParser#tokens` are used outside of code highlighting.

If I replace the code for

`YARD::Parser::Ruby::TokenResolver#initialize`

with

```ruby
def initialize(source, namespace = Registry.root)
  lexer = Ripper::Lexer.new(source)
  # below trims 'on_' from symbols and switches inner array order
  @tokens = lexer.lex.map { |t| [ t[1][3..-1].to_sym , t[2] , t[0] ] }
  raise ParserSyntaxError if lexer.error? || ( @tokens.empty? && !source.empty? )
  @default_namespace = namespace
end
```

Everything seems to work; it passes tests on Ruby 2.3 & 2.2, but I haven't checked to see about a heredoc issue I've seen reference to.  It requires no changes to `YARD::Parser::Ruby::RubyParser` or `YARD::Parser::Ruby::RipperParser`.

Another question is rather than not highlight the code on a parse error, instead, log a warning, error, etc, and let the highlighting pickup what it can. This would allow more highlighting when doc'ing Ruby Core and Std-Lib (and probably other code).

FYI, originally, I made changes to `RipperParser` to pick up %i, %I, %w, and %W, but I came to the conclusion that it would be easier to let the Ripper Lexer do it.

Lastly, I haven't even thought about using it with the 'legacy system'.

Thoughts?

**Comment by MSP-Greg** [comment] 2016-08-07 20:22
@lsegal I just checked Ripper from 2.0 thru 2.4.  The `error?` method was added in 2.2.  Previous to that, it looks like (only) callbacks (`#compile_error`, `#warn` & `#warning`) can be use to detect parse errors.

If not for error detection, one could simply use `Ripper.lex`.

**Comment by lsegal** [comment] 2016-08-07 21:21
@MSP-Greg I think you're conflating multiple issues here. This one is specific to parsing qword and qsymbol literals, which is separate from parse errors. Let's stick to the issue at hand. If you want to raise another issue (highlighting of code by lexing) please open a separate thread. As a sidenote, lexing will still stop at the first parse error, so using tokenization won't highlight syntactically invalid Ruby (specifically, it will stop at the invalid tokens). No need to discuss that separate issue here, though.

This specific issue needs to be fixed in the parser. Unfortunately it does not look like there are equivalent word_literal / symbol_literal nodes in Ruby, which will make this more difficult to implement correctly.

**Closed** 2016-08-07 22:33 UTC

**Comment by MSP-Greg** [comment] 2016-08-07 23:40
@lsegal Sorry, I was conflating what was required for YARD to parse the value for the constant.  Conversely, once I had the changes to the parser (same as what you did), I wanted to see a bit better highlighting, and it seemed that the Ripper lexer did fine for that need.

Example - make sure to view the source code for #init
https://msp-greg.github.io/test/LiteralTest.html

rb file
https://github.com/MSP-Greg/MSP-Greg.github.io/blob/master/test/literal_test.rb

**Comment by lsegal** [comment] 2016-08-08 00:16
I just added some styling rules for the missing nodes. That should completely resolve this issue.

**Comment by davidsoncasey** [comment] 2016-08-08 15:55
@MSP-Greg @lsegal thanks for the work on this! I was away from the computer all weekend so pretty nice to come back on Monday and see all of this. This is what makes projects like YARD great.

**Comment by davidsoncasey** [comment] 2016-08-08 18:03
I've pulled the most recent changes, and I see the expected behavior when looking at the example when I originally put together the issue. When looking at the generated HTML, I'm still not seeing the `%i` array properly:
![Alt text](https://monosnap.com/file/xo6jHVDVsUnATxEBP32s0likAh4RY9.png)

where I'm expecting to see something along the lines of:
![Alt text](https://monosnap.com/file/E537eET5evz70GEsentA9pM0IShAmP.png)

I'm using the most recent version of YARD and have just regenerated documentation. Any suggestions? Thanks again!

**Comment by MSP-Greg** [comment] 2016-08-08 18:44
@davidsoncasey @lsegal Interesting.  I'm kind of in the middle of something else, but I updated my test, and it's working for me.  But, my code is in my plug-in, not in the YARD code base.  If Loren doesn't get to it first, I'll have a look.

See http://msp-greg.github.io/test/LiteralTest.html

Also, see the source highlighting for the #init method.

I added the git repo info, so the 'Defined In:' file link and the #init method 'GitHub' link show the source file that YARD generated the html from...

**Comment by lsegal** [comment] 2016-08-08 19:38
@davidsoncasey I can't seem to reproduce that. Can you provide a minimal case?

I did push a change that should fix some highlighting colors, but that shouldn't be related to your issue.

**Comment by davidsoncasey** [comment] 2016-08-09 16:06
@lsegal @MSP-Greg I'll see if I can steal enough time at work today to put together a case to demonstrate the issue I'm seeing. And in doing so perhaps I'll resolve it myself.

**Comment by MSP-Greg** [comment] 2016-08-09 16:20
@davidsoncasey You could try the test code I used, copy it from --

https://raw.githubusercontent.com/MSP-Greg/MSP-Greg.github.io/master/test/literal_test.rb

I've removed my changes that matched @lsegal's, so as @lsegal found, we can't duplicate your issue.

There may be a difference in highlighting (compared to my 'LiteralTest' sample), but the displayed text should be the same.

**Comment by MSP-Greg** [comment] 2016-08-10 01:35
@lsegal, @davidsoncasey  I was checked some issues with a Ruby Std-Lib doc set, and I noticed issues with parsing the constants in

https://github.com/ruby/ruby/blob/trunk/lib/rubygems.rb

What seems like similar formatting does work in an updated version of `literal_test.rb`, but breaks in the `rubygems.rb` file.  It appears the last closing character on the literal arrays is being dropped.  Still investigating...

**Comment by lsegal** [comment] 2016-08-10 04:12
@davidsoncasey this may be related to #894, which would be a separate issue with grabbing source from certain nodes. Can you reproduce this with your initial minimal reproduction code?

**Comment by MSP-Greg** [comment] 2016-08-10 23:12
@lsegal  I've got PR ready for this.

It adds a method called by `Handlers::Ruby::ClassVariableHandler` and `Handlers::Ruby::ConstantHandler`.  

At present, I've got it as an instance method in `Handlers::Ruby::Base`.  Is that location alright with you?

I've updates the literal_test rb & html files.  Added all the test cases I could think of.

**Comment by lsegal** [comment] 2016-08-10 23:14
@MSP-Greg for what, exactly? This specific issue should already be resolved.

**Comment by MSP-Greg** [comment] 2016-08-10 23:25
For the fix needed to correctly parse constructs similar to what I found in `rubygems.rb`, as mentioned above,  I updated the file

`https://raw.githubusercontent.com/MSP-Greg/MSP-Greg.github.io/master/test/literal_test.rb`

with several more constants / class variables.

That file has it's 'value text' correctly parsed using the PR (see http://msp-greg.github.io/test/LiteralTest.html) .

I believe the current version will not do so.

**Comment by lsegal** [comment] 2016-08-10 23:31
Feel free to open a PR for this with tests.
