### ISSUE TITLE
Macros only work in yard server, and even then only when you trick it into reloading

### ISSUE THREAD

**Issue by ifreecarve** [lsegal/yard#916] opened 2015-12-01 06:46 UTC
Following the example here:
https://github.com/lsegal/yard/wiki/Tags#attaching-a-macro-to-a-dsl-class-method

I'm trying to create my own documentation macro here:
https://github.com/ifreecarve/nmea_plus/blob/a6030c3d011b3130dd4ce6b16b86b82822796493/lib/nmea_plus/message/base.rb#L15-L17 (currently the latest commit on master branch of https://github.com/ifreecarve/nmea_plus).

It does a weird thing, reproducible every time.

 1. Remove any existing docs, generate static docs, and launch server at the same time.
`$ rm -rfv doc .yardoc && yard && yard server --reload`

 2. Navigate to file:///path/to/nmea_plus/doc/NMEAPlus/Message/NMEA/GBS.html and notice that there is no documentation provided by the macros.
<img width="738" alt="screen shot 2015-12-01 at 1 40 15 am" src="https://cloud.githubusercontent.com/assets/583459/11494071/fa8b5538-97cc-11e5-862a-bf12a8dad0e5.png">

 3. Navigate to the running server (http://localhost:8808/docs/NMEAPlus/Message/NMEA/GBS) and notice that there is no documentation provided by the macros.
<img width="735" alt="screen shot 2015-12-01 at 1 41 41 am" src="https://cloud.githubusercontent.com/assets/583459/11494075/05018d70-97cd-11e5-8560-d333412a19e2.png">

 4. Modify that ruby file in a way that should not affect documentation whatsoever
`$ echo " " >> lib/nmea_plus/message/nmea/gbs.rb `

 5. Refresh http://localhost:8808/docs/NMEAPlus/Message/NMEA/GBS and notice that the macro documentation has now appeared.
<img width="744" alt="screen shot 2015-12-01 at 1 43 24 am" src="https://cloud.githubusercontent.com/assets/583459/11494077/0bbd942e-97cd-11e5-9c2f-bdd8af2694b7.png">

**Comment by ifreecarve** [comment] 2015-12-01 06:48
Notice that it correctly inherited the `field_reader` function, but apparently not the yard macro supposedly `attach`ed to it.

**Comment by lsegal** [comment] 2015-12-01 07:39
This has to do with file order. Due to the way docstrings are evaluated, macros are parsed and executed as they appear. It's likely that the file with the macro in it, or in this case, the superclass that contains the macro class method, is being parsed after the GBS class. That's why parsing your codebase twice (with the initial database still loaded) works. Running `yard && yard -c` would also have worked here.

The quick fix is to add the following to your .yardopts file:

```
lib/nmea_plus/message/nmea/base_nmea.rb lib/**/*.rb
```

Better docs on macros could help make this more clear.

**Comment by ifreecarve** [comment] 2015-12-01 15:45
Is there a way to show the order in which files were loaded by yard?  

Speaking of docs... I spent a lot of time trying every permutation of `@!macro` (http://www.rubydoc.info/gems/yard/file/docs/GettingStarted.md#Macros) and `@macro` (https://github.com/lsegal/yard/wiki/Tags).  I assumed that the problem was me messing those up somehow, and went down a rabbit hole.

I also had trouble figuring out how the command line worked.  `yard --help` wasn't helpful.  It was only because you mentioned `yard -c` (which isn't discussed in any of your docs) that I puzzled out the fact that by default `yard` does `yard doc`... so `yard help doc` is what I needed.

**Comment by lsegal** [comment] 2015-12-05 03:49
I would accept a patch to the CLI routing code that mentioned something along the lines of

> Type `yard <command> --help` for more information about a command.

But I believe this specific issue is working as intended.

**Comment by ifreecarve** [comment] 2015-12-05 05:51
Well, the problem I'm describing with the CLI is that when you type `yard` what's really happening is `yard doc`.  So if you don't know that in advance, you won't realize that you need to type `yard doc --help` for help.

**Comment by lsegal** [comment] 2016-04-15 06:28
The `yard` command aliasing to `yard doc` is a legacy feature that, unfortunately, can't be changed anymore (yard used to just be a single command). Marking as closed since this works as intended, but I understand the unfortunate confusion.

**Closed by lsegal** 2016-04-15 06:28 UTC
Labels: Works as Intended
