### ISSUE TITLE
Yard isn't parsing tags for one of my classes

### ISSUE THREAD

**Issue by rg-3** [lsegal/yard#1310] opened 2020-02-23 04:11 UTC
While generating documentation for my project locally, I noticed for one particular class, many tags weren't being parsed by Yard and instead were displayed as-is. It can be observed on [rubydoc](https://rubydoc.info/gems/trip.rb/Trip) as well as locally when i run `yardoc`.

I tried the latest version of yard, and a few versions prior but problem remained.

Did something in Yard change? 

## Steps to reproduce

This is the minimal reproduction for the issue. I've done my best to remove
all extraneous code and unique environment state on my machine before providing
these steps:

1. git clone https://github.com/rg-3/trip.rb
2. cd trip.rb
3. bundle install --path=.bundle
4. bundle exec yardoc
5. xdg-open doc/index.html and go to class docs for `Trip` class.

**Comment by rg-3** [comment] 2020-02-23 04:33
I added the Trip.rb repo to rubydoc.info and added a [.yardopts](https://github.com/rg-3/trip.rb/blob/master/.yardopts) file but as you can see it [didn't help](https://rubydoc.info/github/rg-3/trip.rb/master/Trip).

**Comment by lsegal** [comment] 2020-02-23 05:02
I'm not sure if anything specifically changed in YARD vs. the Ruby environment / ripper parser in 2.7.x, or if this was ever working, but I _do_ see inconsistent use of indentation spaces before the tags. See [Trip#initialize](https://github.com/rg-3/trip.rb/blob/master/lib/trip.rb#L26-L40) (which renders incorrectly) vs. [Trip#pause_when](https://github.com/rg-3/trip.rb/blob/master/lib/trip.rb#L42-L52) (which renders correctly).

The easy workaround as we do more diagnosis of the root cause (did this change? is this expected?) would be to stick with using 1 space to separate the comment token (`#`) from your docstring data.

My general assumption here is that your markdown formatter (specifically redcarpet) is seeing those 2 spaces (1st one is stripped) and treating the text as a code block. It's probably throwing YARD off in a different but similar way.

**Comment by lsegal** [comment] 2020-02-23 05:51
Looking into this further, the indentation detection logic used to parse tags hasn't changed in 8 years:

https://github.com/lsegal/yard/blame/8e82a8ab27f2e711bf555bb6ba0c037a1eb3ccfb/lib/yard/docstring_parser.rb#L165

It's certainly possible some other new environment change is tripping up this logic, but reading that code indicates to me that your docs should have rendered this way for quite a while. 

Basically, `META_MATCH` is looking for "@" at the start of a line. The front space isn't getting stripped (this might be the part that changed?) and so it's not detecting as a tag.

Realistically this _does_ make sense. Top-level tags shouldn't have any indentation prior to them or it becomes difficult for YARD to differentiate tags from code blocks, consider the following, where it's not clear whether the docstring is a tag or code block:

```ruby
#    @ivar = 2
def foo; end
```

In other words, this seems like intended behavior to me.

**Comment by rg-3** [comment] 2020-02-23 09:16
Thanks ! Removing the extra leading white space fixed it ([commit](https://github.com/rg-3/trip.rb/commit/53f40d80871951afc02b391f27302af95fd1587a) and [rubydoc.info](https://rubydoc.info/github/rg-3/trip.rb/master/Trip))

> Basically, META_MATCH is looking for "@" at the start of a line. The front space isn't getting stripped (this might be the part that changed?) and so it's not detecting as a tag.

I guess so, I could have sworn I've written directives this way before. Maybe not, though.

> Realistically this does make sense. Top-level tags shouldn't have any indentation prior to them or it becomes difficult for YARD to differentiate tags from code blocks, consider the following, where it's not clear whether the docstring is a tag or code block:

Yeah, that makes sense. Could Yard at least omit some kind of warning, or some how do a better job as I've been blissfully unaware this was an even issue until I ran `yardoc` locally :)

**Comment by lsegal** [comment] 2020-05-03 21:14
Marking this as closed since this is intended behavior in YARD.

**Closed by lsegal** 2020-05-03 21:14 UTC
