### ISSUE TITLE
Putting blocks with parameters in code examples disables code highlighting

### ISSUE THREAD

**Issue by Hubro** [lsegal/yard#781] opened 2014-06-06 20:37 UTC
Highlights just fine:

    file = Rozi.open_file_for_writing("file_path.wpt")
    file.write("Østre aker\n")   # Writes "Østre aker\r\n" in ISO-8859-1.

No code highlighting (!!!):

    Rozi.open_file_for_writing("file_path.wpt") { |file|
      file.write("Østre aker\n")
    }

Highlights fine again:

    Rozi.open_file_for_writing("file_path.wpt") {
      file.write("Østre aker\n")
    }

The same does for `do ... end`, and the parameter name doesn't seem to matter.

---

Ruby 2.0.0
Yard 0.8.7.4

**Comment by lsegal** [comment] 2016-07-06 11:07
Can't reproduce this so marking it as closed. If you can provided an updated minimal reproduction case, I would look at it.

**Closed by lsegal** 2016-07-06 11:07 UTC
Labels: Bug
