### ISSUE TITLE
Markdown anchor links / tags in README not correctly generated in HTML

### ISSUE THREAD

**Issue by whopper** [lsegal/yard#1032] opened 2016-11-04 19:44 UTC
Hello again! Recently, I noticed that in the generated README (index.html) for a given project, the markdown links in its table of contents don't properly link to their respective sections. The links behave properly on GitHub, so I'm wondering if this is a bug in the markdown -> html translation in YARD. (Everything else works brilliantly):

## Steps to reproduce

1. An example markdown anchor that doesn't behave once converted into HTML by YARD:
```
#### Table of Contents
[Setup - The basics of getting started with apache][Setup]
```

A header which is linked to via the anchor link above:
```
## Setup
...
```

## Actual Output

After this README is generated, we end up with the link pointing to the following anchor:
```
<a href="#module-description">Module description - What is the apache
module, and what does it do?</a>
```

However, the header itself was given the ID `label-Module+description`:
```
<h2 id="label-Module+description">Module description</h2>
```

Thus, clicking the link in the table of contents achieves nothing.

## Expected Output

The `id` of the header should match the anchor that the table of contents link is pointing to.

## Environment details:

* OS: OSX 10.11
* Ruby version (`ruby -v`): 2.1.6p336
* YARD version (`yard -v`): 0.9.5
* Relevant software dependency/versions:
  * This is an issue in puppetlabs/puppet-strings, but probably isn't limited to that project.

I have read the [Contributing Guide][contrib].

[contrib]: https://github.com/lsegal/yard/blob/master/CONTRIBUTING.md

**Comment by lsegal** [comment] 2016-11-14 21:42
In this case, your markdown library would be relevant here. In general I would say that this is likely a markdown library issue. YARD doesn't deal with rendering markup to HTML, it delegates to your markup library. If the link is being built incorrectly, that's likely not a YARD issue.

**Comment by whopper** [comment] 2016-12-07 21:51
Sorry @lsegal, I missed your request! I'm seeing this issue with the `redcarpet` gem. If you create a dummy project with a Gemfile including the following:

```
gem 'redcarpet'
gem 'yard', '~> 0.9.5'
```

... and then make a README with the bits I posted in the original issue, you should have the same problem I did.

Thanks a ton for looking into this! Sorry I took so long to respond :)

**Comment by lsegal** [comment] 2016-12-07 23:15
@whopper this seems like a redcarpet issue then. I'd recommend trying with another Markdown library.

As a sidenote, ToC already gets generated by YARD.

**Comment by lsegal** [comment] 2017-01-07 19:02
Marking as closed since this is a third-party issue. If you can provide reproduction without redcarpet or code in YARD that causes this issue, feel free to reopen.

**Closed by lsegal** 2017-01-07 19:02 UTC
Labels: Needs Feedback

**Comment by olleolleolle** [comment] 2017-08-19 13:13
Hello!

I got here via some digging in OctoKit.rb, a gem which has [a `diskfile` override in their yard template](https://github.com/octokit/octokit.rb/blob/0f13944e8dbb0210d1e266addd3335c6dc9fe36a/yard/default/layout/html/setup.rb#L5-L14).

```ruby
  # Hack our way to working hash anchors for the README.
  # GitHub generates header links as #some-thing and YARD
  # generates them as #Some_thing so this makes the necessary
  # changes to the generate docs so the links work both on
  # GitHub and in the documentation.
  if @file.name == "README"
    data.scan(/href\=\"\#(.+)\"/).each do |bad_link|
      data.gsub!(bad_link.first, bad_link.first.capitalize.gsub('-', '_'))
    end
  end
```



---

An example:

- [Hutch](https://github.com/gocardless/hutch) README on GitHub, which creates kebab-cased `id` in headings: https://github.com/gocardless/hutch#project-maturity
- YARD-rendered README, with "Snake_Cased" `id` in headings: http://www.rubydoc.info/gems/hutch#Project_Maturity (note: the value of the `id` is "Project_Maturity", so that a `#project-maturity` anchor points at nothing)
