### ISSUE TITLE
Undefined method 'type' in `ruby_parser.rb:460`

### ISSUE THREAD

**Issue by gettalong** [lsegal/yard#846] opened 2015-03-19 21:01 UTC
I get the following error when running a tool that uses Yard instead of RDoc on my codebase:

~~~
ruby-2.2.0/gems/yard-0.8.7.6/lib/yard/parser/ruby/ruby_parser.rb:460:in `block (2 levels) in on_params': undefined method `type
' for 64048:Fixnum (NoMethodError)
        from /home/thomas/.rvm/gems/ruby-2.2.0/gems/yard-0.8.7.6/lib/yard/parser/ruby/ruby_parser.rb:458:in `map!'
        from /home/thomas/.rvm/gems/ruby-2.2.0/gems/yard-0.8.7.6/lib/yard/parser/ruby/ruby_parser.rb:458:in `block in on_params'
        from /home/thomas/.rvm/gems/ruby-2.2.0/gems/yard-0.8.7.6/lib/yard/parser/ruby/ruby_parser.rb:454:in `map!'
        from /home/thomas/.rvm/gems/ruby-2.2.0/gems/yard-0.8.7.6/lib/yard/parser/ruby/ruby_parser.rb:454:in `on_params'
        from /home/thomas/.rvm/gems/ruby-2.2.0/gems/yard-0.8.7.6/lib/yard/parser/ruby/ruby_parser.rb:50:in `parse'
        from /home/thomas/.rvm/gems/ruby-2.2.0/gems/yard-0.8.7.6/lib/yard/parser/ruby/ruby_parser.rb:50:in `parse'
        from /home/thomas/.rvm/gems/ruby-2.2.0/gems/yard-0.8.7.6/lib/yard/parser/ruby/ruby_parser.rb:15:in `parse'
        from /home/thomas/.rvm/gems/ruby-2.2.0/gems/yard-0.8.7.6/lib/yard/parser/source_parser.rb:439:in `parse'
        from /home/thomas/.rvm/gems/ruby-2.2.0/gems/yard-0.8.7.6/lib/yard/parser/source_parser.rb:44:in `block in parse'
        from /home/thomas/.rvm/gems/ruby-2.2.0/gems/yard-0.8.7.6/lib/yard/logging.rb:70:in `capture'
        from /home/thomas/.rvm/gems/ruby-2.2.0/gems/yard-0.8.7.6/lib/yard/parser/source_parser.rb:43:in `parse'
        from /home/thomas/.rvm/gems/ruby-2.2.0/gems/yard-0.8.7.6/lib/yard/parser/source_parser.rb:368:in `parse_in_order'
        from /home/thomas/.rvm/gems/ruby-2.2.0/gems/yard-0.8.7.6/lib/yard/parser/source_parser.rb:107:in `block in parse'
        from /home/thomas/.rvm/gems/ruby-2.2.0/gems/yard-0.8.7.6/lib/yard/logging.rb:166:in `enter_level'
        from /home/thomas/.rvm/gems/ruby-2.2.0/gems/yard-0.8.7.6/lib/yard/parser/source_parser.rb:106:in `parse'
        from /home/thomas/.rvm/gems/ruby-2.2.0/gems/yard-0.8.7.6/lib/yard.rb:18:in `parse'
~~~

**Comment by lsegal** [comment] 2015-03-19 21:23
Duplicate of #825. This is fixed in Ruby 2.2.1.

**Closed by lsegal** 2015-03-19 21:23 UTC
Labels: Duplicate, Invalid
