### ISSUE TITLE
Behavior of @api depends on order that YARD processes files

### ISSUE THREAD

**Issue by DavidEGrayson** [lsegal/yard#799] opened 2014-09-16 23:21 UTC
I'd like to report a bug with @api tag.  The [documentation of the @api tag](http://rubydoc.info/gems/yard/file/docs/Tags.md#api) says:

> If it is applied on a namespace (module or class), it will automatically be applied to all children objects of that namespace unless it is redefined on the child object.

However, that description doesn't seem to reflect the way that the @api tag actually behaves, which depends on what order YARD processes files.

To reproduce the bug, I used jruby 1.7.15 in Windows and yard 0.8.7.4.  I made a directory with the following four files:

File `foo_a.rb`:

```ruby
module Foo
  class A
  end
end
```

File `foo_b.rb`:

```ruby
# @api public
module Foo
  class B
  end
end
```

File `foo_c.rb`:

```ruby
module Foo
  class C
  end
end
```

File `.yardopts`:

```text
foo_a.rb
foo_b.rb
foo_c.rb
--api public
```

Since the module Foo is marked as being in the public API (in `foo_b.rb`), I would expect to see `Foo::A`, `Foo::B`, and `Foo::C` all show up in the generated documentation when I run the command `yard` (with no arguments).  Instead, when I run that command, the docs only show B and C, and they don't show A.

If I change `.yardopts` so that `foo_b.rb` is the first file, then I do get the expected results.  If I change `.yardopts` so that `foo_b.rb` is last, then both A and C are missing from the documentation.

I haven't looked at the code, but it seems like YARD is deciding too early a class is public or not.  I think it should read all the files in, construct the namespace hierarchy, and then evaluate which things are public and which things are not.  The result shouldn't depend on the order that YARD processes the files.  In general, if there is ever a situation where the order of the files matters, I think YARD should emit a warning about it and give the user some way to fix it.

**Comment by lsegal** [comment] 2016-07-06 03:36
Marking this as closed (see [CONTRIBUTING.md](https://github.com/lsegal/yard/blob/master/CONTRIBUTING.md) for reason why this was closed) since it is a feature request with no PR. I would be willing to look at a PR to add `@api` tags more intelligently.

**Closed by lsegal** 2016-07-06 03:36 UTC
Labels: Feature

**Comment by DavidEGrayson** [comment] 2016-07-06 04:36
I would suggest keeping this issue open until it is fixed.  That way people can easily see what issues the project has, instead of having to look in the closed issues list, which will contain things that not actually real issues.

**Comment by DavidEGrayson** [comment] 2016-07-23 19:28
Okay, I reread your comment more carefully and it seems like you consider this to be a request for a new feature.  I consider it to be a bug report, so I think it should be re-opened.  There is a mismatch between what the documentation says and how @api tag actually works, and the order in which files are processed affects how YARD behaves.

**Comment by lsegal** [comment] 2016-07-23 19:47
The only "bug" here is the loose usage of the term automatically when describing transitive tag behavior. I've changed this, but this will not change the behavior of transitive tags. Transitive tags are behaving as intended (applying *immediately* on the object). Changing the behavior to apply on all objects would require a whole new code path and logic.
